### ISSUE TITLE
Relative path issue.

### ISSUE THREAD

**Issue by RangerOnMars** [tup-robomaster/TUP-InfantryVision-2022#1]
Execute the binary file outside build directory will lead to:
terminate called after throwing an instance of 'InferenceEngine::GeneralError'
  what():  Model file ../model/opt-0517-001.xml cannot be opened!

**Comment by dishierweidu** [comment]
This may be due to copying the build directory when copying the program.  It can be solved by deleting the build directory, rebuilding and then rebooting
