### ISSUE TITLE
如果能写一份串口通信协议说明文档就更好了

### ISSUE THREAD

**Issue by emoPointer** [tup-robomaster/TUP-InfantryVision-2022#4]

**Comment by RangerOnMars** [comment]
可以捏，是只需要串口通讯协议部分的文档还是需要整个模块的文档？

**Comment by emoPointer** [comment]
> 可以捏，是只需要串口通讯协议部分的文档还是需要整个模块的文档？

感谢大佬啊，最近跑了一下，和电控那边已经差不多摸清楚了通信协议，但在getmod中read读取串口内容的时候，数组rdata被分成了两份，原本read是读50位数据，发现被分成了32位和18位，甚是不解，如果大佬有空的话，麻烦大佬写一下整个模块的吧，想后面也试试外置陀螺仪，实在感谢大佬，让我们战队实现了有视觉的梦想( ﹡ˆoˆ﹡ )

**Comment by emoPointer** [comment]
> > 可以捏，是只需要串口通讯协议部分的文档还是需要整个模块的文档？
> 
> 感谢大佬啊，最近跑了一下，和电控那边已经差不多摸清楚了通信协议，但在getmod中read读取串口内容的时候，数组rdata被分成了两份，原本read是读50位数据，发现被分成了32位和18位，甚是不解，如果大佬有空的话，麻烦大佬写一下整个模块的吧，想后面也试试外置陀螺仪，实在感谢大佬，让我们战队实现了有视觉的梦想( ﹡ˆoˆ﹡ )

当我强行将32和18连起来的时候，发现crc校验又过不去了

**Comment by xiaorui3** [comment]
> 可以捏，是只需要串口通讯协议部分的文档还是需要整个模块的文档？

新人求要串口通信文档(*´I`*)
